export type {
  AddMemberRequest,
  AnalysisCriterionDto,
  AnswerFormatsValue,
  AssignmentAttachmentDto,
  AssignmentAttachmentKindName,
  AttachmentKindName,
  AssignmentDto,
  AssignmentGroupOverviewDto,
  AttemptStatusName,
  AttendanceBucketDto,
  AttendanceSummaryDto,
  AttritionByGroupDto,
  AttritionByTeacherDto,
  AttritionListParams,
  AttritionRowDto,
  AttritionSortName,
  AttritionSummaryDto,
  MembershipEventKindName,
  AuthoringOptionDto,
  AuthoringQuestionDto,
  AuthResponse,
  AvailableTestDto,
  CenterLeaderboardDto,
  ChatMessageDto,
  ConversationDto,
  CoverageDetailDto,
  CoverageStatusDto,
  CourseDto,
  CourseLessonDto,
  CourseModuleDto,
  CourseTreeDto,
  CourseWriteRequest,
  CreateAssignmentRequest,
  CreateDiscountRequest,
  CreateGroupResponse,
  CreateHolidayRequest,
  CreateMessageTemplateRequest,
  CreateTariffRequest,
  CreateTestRequest,
  CreateUserRequest,
  CreateUserResponse,
  CuratorCandidateDto,
  DayOfWeekName,
  DevQuickLoginAccount,
  DevQuickLoginList,
  DirectMessageAttachmentDto,
  DirectMessageDto,
  DiscountKindName,
  FinanceSettingsDto,
  GradeSubmissionRequest,
  /* ===== "Xabarlar" paneli ===== */
  GroupBroadcastDto,
  /* ===== /"Xabarlar" paneli ===== */
  GroupChatAccessDto,
  GroupChatChannelName,
  GroupChatAttachmentDto,
  GroupChatMessageDto,
  GroupChatPageDto,
  GroupChatReadResultDto,
  GroupChatThreadDto,
  /* ===== R21b · guruh kategoriyasi ===== */
  GroupCategoryDto,
  GroupCategoryWriteRequest,
  /* ===== /R21b ===== */
  GroupDto,
  GroupLeaderboardDto,
  /* ===== R33 + R40 · kim mas'ul ===== */
  GroupStaffRoleName,
  GroupMemberDto,
  GroupTypeName,
  GroupWriteRequest,
  GroupAttritionDetailDto,
  /* ===== Bayram kalendari ===== */
  HolidayDto,
  HolidayImpactDto,
  /* ===== /Bayram kalendari ===== */
  LeaderboardRowDto,
  LeaderboardScopeName,
  LessonAssetDto,
  LessonAssetKindName,
  LessonAssetUploadFields,
  LessonKindName,
  LessonLockReasonName,
  LessonQuestionDto,
  LessonWriteRequest,
  LiveKitJoinDto,
  LiveSessionDto,
  MarkGroupChatReadRequest,
  MarkReadResultDto,
  MediaAccessTicketDto,
  MemberStatusName,
  MessagePageDto,
  MessageTemplateDto,
  ModuleWriteRequest,
  MoveMemberRequest,
  MoveMemberResponse,
  MyRankDto,
  MyResultDto,
  OpenPeriodRequest,
  OpenPeriodResult,
  PagedResult,
  PauseMemberRequest,
  RemoveMemberRequest,
  PaymentAgingBucketDto,
  PaymentAgingBucketName,
  PaymentBlockDto,
  PaymentBlockScopeName,
  PaymentDto,
  PaymentGroupSummaryDto,
  PaymentMethodName,
  PaymentMethodSummaryDto,
  PaymentMonthSummaryDto,
  PaymentReceiptDto,
  PaymentStatusName,
  PaymentSummaryDto,
  PaymentSummaryKpiDto,
  PaymentTransactionDto,
  PaymentTransactionKindName,
  PhoneCodeRequest,
  PhoneCodeResponse,
  PhoneVerifyRequest,
  PositionDto,
  ProblemDetails,
  QuestionAnswerRequest,
  RecordingDto,
  RecordingLinkDto,
  RecordingListItemDto,
  RecordingLiveStatusDto,
  RecordingSectionDto,
  RecordingStatusName,
  RecordPaymentRequest,
  RefreshRequest,
  ReopenSubmissionRequest,
  ReorderRequest,
  ReversalDto,
  ReversePaymentRequest,
  SaveAnalysisCriterionRequest,
  SaveOptionRequest,
  SaveQuestionRequest,
  SaveSessionReviewRequest,
  SaveSessionReviewScoreRequest,
  ScheduleChangeSummary,
  ScheduledSessionDto,
  SendDirectMessageRequest,
  SendGroupBroadcastRequest,
  SendGroupChatMessageRequest,
  SessionReviewDto,
  SessionReviewScoreDto,
  SessionReviewVerdictName,
  SessionStatusName,
  SessionTypeName,
  SetExemptRequest,
  SettingConstraintsDto,
  SettingDto,
  SettingFormatName,
  SettingGroupDto,
  SettingGroupKey,
  SettingKindName,
  SettingOriginName,
  SettingsPageDto,
  StartAttemptDto,
  StudentAccountDto,
  StudentAssignmentDto,
  StudentDiscountDto,
  StudentSubmissionDto,
  SubmissionDto,
  SubmissionFeedbackFileDto,
  SubmissionFileDto,
  StudentStatsDto,
  SubmissionOverviewDto,
  SubstituteOfferRowDto,
  TeacherAvailabilityDetailDto,
  TeacherAvailabilityListParams,
  TeacherAvailabilityRowDto,
  TeacherAvailabilitySortName,
  TeacherAvailabilitySummaryDto,
  TeacherCheckinStatusName,
  TeacherReviewOverviewDto,
  SubmissionStatusName,
  SubmitTestRequest,
  TakeOptionDto,
  TakeQuestionDto,
  TakeTestDto,
  TariffDto,
  TestAuthoringDto,
  TestDto,
  TestKindName,
  TestResultRowDto,
  UpdateAssignmentRequest,
  UpdateDiscountRequest,
  UpdateFinanceSettingsRequest,
  UpdateGroupResponse,
  UpdateMessageTemplateRequest,
  UpdateSettingRequest,
  UpdateTariffRequest,
  UpdateTestRequest,
  UpdateUserRequest,
  UserDetailsDto,
  UserDto,
  UserRoleName,
  WaiveRequest,
} from './api'

/* ===== WAVE 2 · FOYDALANUVCHI (wave2/users) =====

   ★ NEGA ALOHIDA BLOK, nega yuqoridagi alifbo ro'yxatiga QO'SHILMADI:
   bu faylga ikki tarmoq (`wave2/users` va `wave2/groups`) AYNI VAQTDA
   qo'shadi. Alifbo bo'yicha aralashtirilgan 15 ta qo'shimcha qator merge
   paytida to'qnashuv beradi; bitta uzluksiz blok esa hech qachon. Tartib
   blok ICHIDA alifbo bo'yicha saqlanadi.                                */
export type {
  CreateStudentNoteRequest,
  ProfileAssignmentDto,
  ProfileAttendanceDto,
  ProfileFinanceDto,
  ProfileGroupDto,
  ProfilePeriodDto,
  ProfileStudyDto,
  ProfileTelegramDto,
  ProfileTestDto,
  StudentNoteDto,
  TelegramUnlinkRequest,
  TelegramUnlinkResponse,
  UpdateStudentNoteRequest,
  UserProfileDto,
} from './api'
/* ===== /WAVE 2 · FOYDALANUVCHI ===== */

/* ===== R31 · DARSLAR JADVALI AGREGATI =====

   ★ NEGA ALOHIDA BLOK, alifbo ro'yxatiga qo'shilmadi: yuqoridagi
   `wave2/users` bloki bilan AYNI sabab — bu faylga bir necha tarmoq ayni
   vaqtda qo'shadi va alifbo bo'yicha aralashtirilgan bitta qator merge
   paytida to'qnashuv beradi.                                            */
export type { SessionStatsDto } from './api'
/* ===== /R31 ===== */

/* ===== R35/R36 · BILDIRISHNOMA =====

   ★ NEGA ALOHIDA BLOK: yuqoridagi bloklar bilan AYNI sabab — bu faylga
   bir necha tarmoq ayni vaqtda qo'shadi.                              */
export type {
  DeleteNotificationsRequest,
  MarkNotificationsReadRequest,
  NotificationDeleteResultDto,
  NotificationDto,
  NotificationKindName,
  NotificationPageDto,
  NotificationReadResultDto,
  NotificationUnreadDto,
} from './api'
/* ===== /R35/R36 ===== */

/* ===== 2026-08-15 · O'Z PROFIL RASMI (2026-08-17 da qisqartirildi) ===== */
export type { AvatarUploadedDto } from './api'
/* ===== /O'Z PROFIL RASMI ===== */

/* ===== 2026-08-17 · "MENING GURUHIM" OYNASI ===== */
export type { ClassroomDto, ClassroomGroupDto, ClassroomMemberDto } from './api'
/* ===== /"MENING GURUHIM" OYNASI ===== */

/* ===== Bosqich 4 · Oylik hisoblash (2026-08-16) ===== */
export type {
  CreatePayrollAdjustmentRequest,
  CreateTeacherRateRequest,
  PayrollAdjustmentDto,
  PayrollApprovalStatusName,
  PayrollDetailDto,
  PayrollPeriodActionRequest,
  PayrollSessionRowDto,
  PayrollSummaryDto,
  PayrollSummaryRowDto,
  TeacherRateDto,
  UpdateTeacherRateRequest,
} from './api'
/* ===== /Bosqich 4 ===== */

export { GroupChatHubEvent, GroupChatHubMethod, HubEvent, HubMethod } from './realtime'
export { NotificationHubEvent } from './realtime'
export type {
  GroupChatHubEventName,
  GroupChatHubMethodName,
  HubEventName,
  HubMethodName,
  HubStatus,
  HandRaisedPayload,
  NotificationHubEventName,
  PresenceChangedPayload,
  PresenceEntry,
  SessionEndedPayload,
} from './realtime'
