export { GROUP_TABS, visibleGroupTabs } from './model/tabs'
export type { GroupTabDef, GroupTabKey } from './model/tabs'
export { heldSummary } from './model/calendar'
export { default as AttendanceTab } from './ui/AttendanceTab.vue'
export { default as BoardTab } from './ui/BoardTab.vue'
export { default as ChatTab } from './ui/ChatTab.vue'
export { default as GradesTab } from './ui/GradesTab.vue'
export { default as GroupTabs } from './ui/GroupTabs.vue'
export { default as LessonsTab } from './ui/LessonsTab.vue'
export { default as TasksTab } from './ui/TasksTab.vue'
export { default as TestsTab } from './ui/TestsTab.vue'
export { default as UpNextBanner } from './ui/UpNextBanner.vue'
