using System.Globalization;
using Npgsql;
using Zinnur.Migration.Reporting;

namespace Zinnur.Migration.Pipeline;

/// <summary>
/// ========================================================================
/// IDENTITY KETMA-KETLIKLARINI TO'G'RILASH — KO'CHIRISHNING OXIRGI QADAMI
/// ========================================================================
///
/// ★ MUAMMO: eski <c>id</c> lar ATAYLAB saqlanadi (qaror sabablari
/// hujjatda). Lekin v2 ustunlari <c>GENERATED BY DEFAULT AS IDENTITY</c> —
/// oshkor qiymat yozilganda ketma-ketlik O'ZI SURILMAYDI. Ya'ni
/// ko'chirishdan keyin ilova birinchi yangi qatorni yozmoqchi bo'lganda
/// ketma-ketlik hamon 1 dan boshlaydi va DARHOL
/// "duplicate key value violates unique constraint PK_..." beradi.
///
/// ★ BU XATO ENG YOMON PAYTDA CHIQADI: ko'chirish "muvaffaqiyatli"
/// tugagan, tizim ochilgan, birinchi foydalanuvchi ro'yxatdan o'tmoqchi.
/// Shuning uchun to'g'rilash ko'chirishning MAJBURIY qadami va tekshiruv
/// hisobotida ham qayta nazorat qilinadi.
///
/// <c>setval(seq, max_id, true)</c> — keyingi qiymat <c>max_id + 1</c>.
/// Jadval bo'sh bo'lsa <c>setval(seq, 1, false)</c> — keyingi qiymat 1.
/// </summary>
internal static class IdentitySequences
{
    private const string Sql = """
        SELECT c.relname AS table_name,
               a.attname  AS column_name,
               pg_get_serial_sequence(quote_ident(c.relname), a.attname) AS seq
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        JOIN pg_attribute a ON a.attrelid = c.oid
        WHERE n.nspname = 'public'
          AND c.relkind = 'r'
          AND a.attidentity <> ''
          AND a.attnum > 0
        ORDER BY c.relname
        """;

    public static async Task ResetAsync(NpgsqlConnection target, Reporter reporter, CancellationToken ct)
    {
        var items = await ReadAsync(target, ct).ConfigureAwait(false);
        var fixedCount = 0;

        foreach (var (table, column, sequence) in items)
        {
            var setval = string.Create(
                CultureInfo.InvariantCulture,
                $"""
                 SELECT setval('{sequence}',
                               COALESCE((SELECT MAX("{column}") FROM "{table}"), 1),
                               (SELECT COUNT(*) FROM "{table}") > 0)
                 """);

            await using var cmd = new NpgsqlCommand(setval, target);
            await cmd.ExecuteScalarAsync(ct).ConfigureAwait(false);
            fixedCount++;
        }

        reporter.Ok(string.Create(
            CultureInfo.InvariantCulture,
            $"Identity ketma-ketliklari to'g'rilandi: {fixedCount} ta jadval."));
    }

    /// <summary>
    /// Har ketma-ketlikning keyingi qiymati jadvaldagi eng katta
    /// <c>Id</c> dan KATTA ekanini tekshiradi. Bu tekshiruv hisobotining
    /// bir qismi: to'g'rilash o'tkazib yuborilgan bo'lsa darhol ko'rinadi.
    /// </summary>
    public static async Task VerifyAsync(
        NpgsqlConnection target,
        MigrationReport report,
        Reporter reporter,
        CancellationToken ct)
    {
        var items = await ReadAsync(target, ct).ConfigureAwait(false);
        var bad = 0;

        foreach (var (table, column, sequence) in items)
        {
            var check = string.Create(
                CultureInfo.InvariantCulture,
                $"""
                 SELECT COALESCE((SELECT MAX("{column}") FROM "{table}"), 0) AS max_id,
                        (SELECT last_value FROM {sequence})                  AS last_value,
                        (SELECT is_called FROM {sequence})                   AS is_called
                 """);

            await using var cmd = new NpgsqlCommand(check, target);
            await using var reader = await cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);

            if (!await reader.ReadAsync(ct).ConfigureAwait(false)) continue;

            var maxId = reader.GetInt64(0);
            var lastValue = reader.GetInt64(1);
            var isCalled = reader.GetBoolean(2);
            var next = isCalled ? lastValue + 1 : lastValue;

            if (maxId > 0 && next <= maxId)
            {
                report.Fail(string.Create(
                    CultureInfo.InvariantCulture,
                    $"`{table}` ketma-ketligi orqada: keyingi qiymat {next}, eng katta Id {maxId} — birinchi yangi qator dublikat kalit xatosi beradi."));
                bad++;
            }
        }

        if (bad == 0) reporter.Ok("Identity ketma-ketliklari to'g'ri (keyingi qiymat > MAX(Id)).");
    }

    private static async Task<List<(string Table, string Column, string Sequence)>> ReadAsync(
        NpgsqlConnection target,
        CancellationToken ct)
    {
        var items = new List<(string, string, string)>();

        await using var cmd = new NpgsqlCommand(Sql, target);
        await using var reader = await cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);

        while (await reader.ReadAsync(ct).ConfigureAwait(false))
        {
            if (reader.IsDBNull(2)) continue;
            items.Add((reader.GetString(0), reader.GetString(1), reader.GetString(2)));
        }

        return items;
    }
}
